services:
  cs2-deathmatch:
    image: joedwards32/cs2
    container_name: cs2-deathmatch
    stdin_open: true
    tty: true
    environment:
      # Server configuration
      - STEAMAPPVALIDATE=0           # (0 - no validation, 1 - enable validation)
      - CS2_SERVERNAME=CS2 DM | FFA (Mirage) — bims.sh (24 Players)
      - CS2_PORT=27015               # (CS2 server listen port tcp_udp)
      - CS2_LAN=0                    # (0 - LAN mode disabled, 1 - LAN Mode enabled)
      - CS2_MAXPLAYERS=24            # (Max players)
      - CS2_PW                       # (CS2 server password)
      - CS2_CFG_URL=https://github.com/Bims-sh/cs2-dm/releases/latest/download/package.tar.gz
      - CS2_ADDITIONAL_ARGS=+exec deathmatch.cfg
      # Game modes
      - CS2_GAMEALIAS=deathmatch     # (Game type, e.g. casual, competitive, deathmatch. See https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers)
      - CS2_GAMETYPE=0               # (Used if CS2_GAMEALIAS not defined. See https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers)
      - CS2_GAMEMODE=0               # (Used if CS2_GAMEALIAS not defined. See https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers)
      - CS2_MAPGROUP=mg_dm           # (Map pool. Ignored if Workshop maps are defined.)
      - CS2_STARTMAP=de_mirage       # (Start map. Ignored if Workshop maps are defined.)
      # Bots
      - CS2_BOT_DIFFICULTY           # (0 - easy, 1 - normal, 2 - hard, 3 - expert)
      - CS2_BOT_QUOTA=6              # (Number of bots)
      - CS2_BOT_QUOTA_MODE=fill      # (fill, competitive)
      # Logs
      - CS2_LOG=on                   # 'on'/'off'
    env_file: ".env"
    volumes:
      - ./cs2:/home/steam/cs2-dedicated
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
